---
language: java
jdk:
  - oraclejdk8
matrix:
  include:
    - os: linux
      addons:
        sonarcloud:
          organization: "sdorra-github"
      script:
        - mvn -Prun-its clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
    - os: osx
      osx_image: xcode9.3
      script:
        - mvn -Prun-its clean verify
