---
language: java
matrix:
  include:
    - os: linux
      addons:
        sonarcloud:
          organization: "sdorra-github"
      script:
        - mvn -Prun-its clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
    - os: osx
      script:
        - mvn -Prun-its clean verify
