---
language: java
dist: trusty
addons:
  sonarcloud:
    organization: "sdorra-github"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Prun-its clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
